# Generated by Django 4.1.5 on 2023-01-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularities',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='api.team'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('destination_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='api.team')),
                ('former_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='former', to='api.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
            options={
                'unique_together': {('player', 'former_club', 'destination_club', 'date')},
                'index_together': {('player', 'former_club', 'destination_club', 'date')},
            },
        ),
    ]
