# Generated by Django 4.1.5 on 2023-03-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('continent', models.CharField(choices=[('AS', 'Asia'), ('EUR', 'europe'), ('NA', 'north America'), ('SA', 'south America'), ('OC', 'oceania'), ('AFR', 'Africa')], max_length=30)),
            ],
        ),
    ]
