# Generated by Django 4.1.5 on 2023-03-09 18:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='managers', to='utils.country')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_team_goal_count', models.IntegerField(blank=True, null=True)),
                ('guest_team_goal_count', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('status', models.CharField(choices=[('NH', 'not held'), ('OG', 'ongoing'), ('H', 'held')], max_length=10)),
                ('round', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=500)),
                ('main_foot', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=6, null=True)),
                ('post', models.CharField(choices=[('GK', 'GoalKeeper'), ('RB', 'Right Back'), ('CB', 'Center Back'), ('LB', 'Left Back'), ('CM', 'Center Midfielder'), ('RM', 'Right Midfielder'), ('LM', 'Left Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker')], max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('birth_date', models.DateField()),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='players', to='utils.country')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stadiums', to='utils.city')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=500)),
                ('president', models.CharField(max_length=50)),
                ('open_transfer_window', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='utils.country')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='stats_api.manager')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='stats_api.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('L', 'league'), ('KO', 'knockout'), ('C', 'combination')], max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tournaments', to='utils.country')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('destination_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_transfers', to='stats_api.team')),
                ('former_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_transfers', to='stats_api.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats_api.player')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_teams', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seasons', to='stats_api.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession', models.IntegerField()),
                ('corners', models.IntegerField(default=0)),
                ('offsides', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('shots_on_target', models.IntegerField(default=0)),
                ('shot_percentage', models.IntegerField()),
                ('goals', models.IntegerField(default=0)),
                ('complete_pass_percentage', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_match_stats', to='stats_api.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_match_stats', to='stats_api.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tournaments',
            field=models.ManyToManyField(to='stats_api.tournament'),
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('in_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_subs', to='stats_api.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='stats_api.match')),
                ('out_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_subs', to='stats_api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='stats_api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referees', to='utils.country')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saves', models.IntegerField(default=0)),
                ('passes', models.IntegerField(default=0)),
                ('complete_passes', models.IntegerField(default=0)),
                ('dribbles', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('key_passes', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('shots_on_target', models.IntegerField(default=0)),
                ('shot_percentage', models.IntegerField()),
                ('complete_pass_percentage', models.IntegerField()),
                ('own_goals', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=5)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_match_stats', to='stats_api.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_match_stats', to='stats_api.player')),
                ('players_team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_match_stats', to='stats_api.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='stats_api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='assist_referees',
            field=models.ManyToManyField(to='stats_api.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='guest_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='guest_team_match', to='stats_api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='host_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='host_team_match', to='stats_api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='main_referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='matches', to='stats_api.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='matches', to='stats_api.stadium'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='matches', to='stats_api.tournamentseason'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('body_area', models.CharField(choices=[('LF', 'left foot'), ('RF', 'right foot'), ('H', 'head'), ('O', 'other')], max_length=15)),
                ('is_og', models.BooleanField(default=False)),
                ('assist_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='goal_assisted_by_player', to='stats_api.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='stats_api.match')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goal_by_player', to='stats_api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goal_by_team', to='stats_api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('card', models.CharField(choices=[('R', 'red'), ('Y', 'yellow')], max_length=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='stats_api.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='stats_api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='stats_api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Popularities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats_api.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'team')},
                'index_together': {('user', 'team')},
            },
        ),
    ]
