# Generated by Django 4.1.5 on 2023-03-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstats',
            name='chances_missed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='post',
            field=models.IntegerField(default=0),
        ),
    ]
