# Generated by Django 4.1.5 on 2023-03-07 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('stats_api', '0003_manager_remove_team_league_referee_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='country',
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='complete_pass_percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='own_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='red_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='shot_percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='shots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='shots_on_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='yellow_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stadium',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='stadiums', to='utils.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='utils.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='tournaments',
            field=models.ManyToManyField(to='stats_api.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='host',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='tournaments', to='utils.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='managers', to='utils.country'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='players', to='utils.country'),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='blocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='complete_passes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='dribbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='interceptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='key_passes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='passes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referee',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referees', to='utils.country'),
        ),
        migrations.CreateModel(
            name='TeamMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession', models.IntegerField()),
                ('corners', models.IntegerField(default=0)),
                ('offsides', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('shots_on_target', models.IntegerField(default=0)),
                ('shot_percentage', models.IntegerField()),
                ('goals', models.IntegerField(default=0)),
                ('complete_pass_percentage', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_match_stats', to='stats_api.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_match_stats', to='stats_api.team')),
            ],
        ),
    ]
