# Generated by Django 4.1.5 on 2023-03-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0004_alter_player_post_alter_playermatchstats_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playermatchstats',
            unique_together={('player', 'match')},
        ),
    ]
