# Generated by Django 4.1.5 on 2023-03-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0006_goaltype_goal_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.ManyToManyField(to='stats_api.goaltype'),
        ),
    ]
