# Generated by Django 4.1.5 on 2023-03-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0007_alter_goal_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.ManyToManyField(blank=True, null=True, to='stats_api.goaltype'),
        ),
    ]
