# Generated by Django 4.1.5 on 2023-03-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0010_teamtournamentstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.ManyToManyField(blank=True, to='stats_api.goaltype'),
        ),
    ]
